---

- name: install personal desktop packages
  become: yes
  apt:
    name:
      - cava
    state: latest
    update_cache: yes
  tags:
    - desktop

- name: deploy i3 config template
  template:
    src: config/i3/config.j2
    dest: "{{ ansible_user_dir }}/.config/i3/config"
  when: window_manager == "i3"
  tags:
    - changetheme
    - desktop

# EOF
