---

- name: deploy bspwm config template
  template:
    src: config/bspwm/bspwmrc.j2
    dest: "{{ ansible_user_dir }}/.config/bspwm/bspwmrc"
  tags: desktop

- name: deploy i3 config template
  template:
    src: config/i3/config.j2
    dest: "{{ ansible_user_dir }}/.config/i3/config"
  tags: desktop

# EOF
