---

- name: make sure git is installed
  become: yes
  apt:
    name: git
    state: latest
    update_cache: yes

- name: verify git directories
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0755
  loop:
    - "{{ git_dir_personal }}"
    - "{{ git_dir_public }}"

- name: copy git config files
  copy:
    src: "files/.gitconfig"
    dest: "{{ ansible_user_dir }}"
    backup:  yes

# EOF
