---

# run this one for personal (non-work) systems

- name: apply common and personal configurations
  hosts: localhost
  pre_tasks:

    - name: fail if theme is not correct
      fail:
        msg: The theme variable is not one of the correct values [dracula, gruvbox, nord, undefined]
      when: >
        ((theme != "dracula") and (theme != "gruvbox") and
        (theme != "nord") and (theme is not defined)

    - name: fail if window_manager is not correct
      fail:
        msg: The window_manager variable is not one of the correct values [bspwm, i3, undefined]
      when: >
        ((window_manager != "i3") and (window_manager != "bspwm") and
        (window_manager is not defined))

    - name: upgrade packages
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: true

  roles:
    - common
    - personal
  tags:
    - install

# EOF

