---

# run this one for personal (non-work) systems

- name: apply common and personal configurations
  hosts: localhost
  pre_tasks:
    - name: upgrade packages
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: true
  roles:
    - common
    - personal
  tags:
    - install

# EOF

