---

# run this one for personal (non-work) systems

- hosts: localhost

  vars:
    theme: nord

  pre_tasks:

    - name: fail if theme is not valid
      fail:
        msg: theme variable value is not valid [dracula, gruvbox, nord, undefined]
      when: (theme is defined) and (theme not in valid_themes)

    - name: upgrade packages
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: true

  roles:
    - common
    - personal

# EOF

