---

# desktop
theme: gruvbox

# public git dir
git_dir_public: "{{ ansible_user_dir }}/git/public"

# ssh
source_key: "files/ssh/id_ed25519"
dest_key: "{{ ansible_user_dir }}/.ssh/id_ed25519"

# regolith repo key for i3-gaps install
regolith_repo_key_url: https://regolith-desktop.org/regolith.key

# dropbox deb location
dropbox_deb_url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb"
