---

- name: git-ty up
  block:

    - name: make sure git is installed
      become: yes
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: verify git directories
      file: 
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: 0755
      loop:
        - "{{ git_dir_work }}"
        - "{{ git_dir_public }}"

    - name: remove personal git dir
      file:
        path: "{{ git_dir_personal }}"
        state: absent

    - name: copy git config file
      copy:
        src: "files/.gitconfig"
        dest: "{{ ansible_user_dir }}"
        backup:  yes

  tags: git

# end of git block

# EOF
