---

- name: work ssh things and stuff
  block:

    - name: verify/create the .ssh directory 
      file:
        dest: "{{ ansible_user_dir }}/.ssh"
        mode: 0700
        state: directory

    - name: remove personal keys
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: "{{ ansible_user_dir }}/.ssh/id*"

    - name: remove known hosts
      file:
        path: "{{ ansible_user_dir }}/.ssh/known_hosts"
        state: absent

    - name: work private key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600

    - name: work public key
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644

    - name: authorize work key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

    - name: work ssh config
      copy:
        src: "files/ssh/config"
        dest: "{{ ansible_user_dir }}/.ssh/config"
        backup: yes

  tags: ssh
    
# end of ssh block

# EOF
