---

- name: install base packages
  become: yes
  apt:
    name:
      - software-properties-common
      - build-essential
      - git
      - curl
      - neovim
      - nmap
      - ranger
      - shellcheck
      - tree
    state: latest
    update_cache: yes

# EOF
