---

- name: desktop related things
  block:

    - name: install desktop packages
      become: yes
      block:

        - name: common desktop packages
          apt:
            name:
              - bpytop
              - dunst
              - kitty
              - lxappearance
              - neofetch
              - nitrogen
              - picom
              - rofi
              - tty-clock
            state: latest
            update_cache: yes

        - name: alacritty
          block:

            - name: alacritty repo
              apt_repository:
                repo: 'ppa:aslatter/ppa'

            - name: install alacritty
              apt:
                name: alacritty
                state: latest
                update_cache: yes

          tags: alacritty

        # end of alacritty block

        - name: install i3
          block:

            - name: add regolith apt repo key
              get_url:
                url: "{{ regolith_repo_key_url }}"
                dest: /etc/apt/trusted.gpg.d/regolith.asc
                mode: '0644'
                force: true

            - name: add regolith repo
              apt_repository:
                repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
                state: present

            - name: install i3-gaps related packages
              apt:
                name:
                  - i3-gaps
                  - i3lock
                  - i3lock-fancy
                state: latest
                update_cache: yes

        # end of i3 block

    # end of package install block

    - name: set the desktop theme
      block:

        - name: deploy alacritty config template
          template:
            src: config/alacritty/alacritty.yml.j2
            dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml"

        - name: deploy kitty config template
          template:
            src: config/kitty/kitty.conf.j2
            dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"

        - name: deploy nvim config template
          template:
            src: config/nvim/init.lua.j2
            dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
          tags: dev

        - name: deploy rofi config template
          template:
            src: config/rofi/config.rasi.j2
            dest: "{{ ansible_user_dir }}/.config/rofi/config.rasi"

        - name: change dunst theme if given
          copy:
            src: "{{ ansible_user_dir }}/.config/dunst/dunstrc.{{ theme }}"
            dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
            backup: yes

      tags: changetheme

    # end of theme block

  tags: desktop

# end of desktop block

# EOF
