---

- name: install base development packages
  become: yes
  apt:
    name:
      - build-essential
      - python3.10-full
      - python3.10-venv
      - python3-neovim
      - python3-pip
      - shellcheck
      - software-properties-common
    state: latest
    update_cache: yes

- name: create a symbolic link from python to python3.10
  become: yes
  file:
    src: /usr/bin/python3.10
    dest: /usr/local/bin/python
    state: link

- name: install latest stable neovim
  become: yes
  block:

    - name: add neovim ppa repo
      apt_repository:
        repo: ppa:neovim-ppa/stable

    - name: install neovim
      apt:
        name: neovim
        state: latest
        update_cache: yes

  tags: neovim

# end of neovim install block

# EOF
