---

- name: install packages
  become: yes
  apt:
    name:
      - build-essential
      - nodejs
      - npm
      - python3.10-full
      - python3.10-venv
      - python3-neovim
      - python3-pip
      - shellcheck
    state: latest
    update_cache: yes

- name: create a symbolic link from python to python3.10
  become: yes
  file:
    src: /usr/bin/python3.10
    dest: /usr/local/bin/python
    state: link

- name: compile and install neovim
  block:

    - name: install neovim build prerequisites
      become: yes
      apt:
        name:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
        state: latest
        update_cache: yes

    - name: delete neovim repo dir
      file:
        path: "{{ git_dir_public }}/neovim"
        state: absent

    - name: clone neovim repo
      git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ git_dir_public }}/neovim"

    - name: neovim make
      make:
        chdir: "{{ git_dir_public }}/neovim"
        target: CMAKE_BUILD_TYPE=RelWithDebInfo
        params:
          NUM_THREADS: 10

    - name: neovim install
      become: yes
      make:
        chdir: "{{ git_dir_public }}/neovim"
        target: install

  tags: neovim

# end of neovim build block

- name: install n
  become: yes
  npm:
    name: n
    state: latest
    global: yes

- name: latest nodejs
  become: yes
  command: n latest

- name: install neovim in node
  become: yes
  npm:
    name: neovim
    state: latest
    global: yes

- name: clone packer repo
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

- name: deploy neovim plugin config file
  template:
    src: config/nvim/lua/plugs.lua.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/lua/plugs.lua" 

- name: deploy neovim colors config file
  template:
    src: config/nvim/after/plugin/colors.lua.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/after/plugin/colors.lua"

# EOF
