---

- name: set up ssh environment
  block:

    - name: verify/create the .ssh directory 
      file:
        dest: "{{ ansible_user_dir }}/.ssh"
        mode: 0700
        state: directory

    - name: personal private key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600

    - name: personal public key
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644

    - name: authorize personal key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: personal ssh config
      copy:
        src: "files/ssh/config"
        dest: "{{ ansible_user_dir }}/.ssh"
        backup: yes

    - name: copy known_hosts
      copy:
        src: "files/ssh/known_hosts"
        dest: "{{ ansible_user_dir }}/.ssh"
        backup: yes

  tags: ssh

# end of ssh block

# EOF
