---

- hosts: localhost

  vars:
    regolith_repo_key_url: https://regolith-desktop.org/regolith.key

  tasks:

    - name: add regolith apt repo key
      become: yes
      get_url:
        url: "{{ regolith_repo_key_url }}"
        dest: /etc/apt/trusted.gpg.d/regolith.asc
        mode: '0644'
        force: true

    - name: add regolith repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
        state: present

    - name: install i3-gaps related packages
      become: yes
      apt:
        name:
          - i3-gaps
          - i3lock
          - i3lock-fancy
        state: latest
        update_cache: yes

# EOF
