---

vars:
  tailscale_repo_key_url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
  tailscale_repo_url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.tailscale-keyring.list"

- name: install tailscale
  block:

    - name: add tailscale repo key
      get_url:
        url: "{{ tailscale_repo_key_url }}"
        dest: /etc/apt/trusted.gpg.d//tailscale.asc

    - name: add tailscale repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tailscale.asc] {{ tailscale_repo_url }} {{ ansible_distribution_release }} main"
        state: present

    - name: install tailscale
      apt:
        name: tailscale
        state: latest
        update_cache: yes

    - name: bring tailscale up
      command: tailscale up

    - name: enable and start tailscale
      service:
        name: tailscaled
        state: started
        enabled: yes

  tags:
    - tailscale

# end of main block

# EOF
